version: "3.6"

networks:
  backend:

volumes:
  pg_data:
  static:

services:
  app:
    container_name: app_credit_holidays
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - TZ=Europe/Moscow
      - CONFIG_PATH=/app/configs/config.yml
    volumes:
      - static:/app/static
    depends_on:
      pg_credit_holidays:
        condition: service_healthy
    networks:
      - backend

  pg_credit_holidays:
    container_name: pg_credit_holidays
    image: postgres
    restart: always
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=egor
      - POSTGRES_PASSWORD=3601
      - POSTGRES_DB=credit_holidays
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d credit_holidays -U egor -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - backend