postgres:
  host: "pg_credit_holidays"
  port: "5432"
  user: "egor"
  pass: "3601"
  dbname: "credit_holidays"

timeout:
  db_insert: "6s"
  db_select: "3s"
  db_update: "3s"
  db_delete: "3s"

log:
  level: "info"